/// A protocol for types that participate in Score's middleware pipeline.
///
/// `Middleware` defines the contract for request-processing stages that sit
/// between the server and a controller's handler. Each conforming type
/// represents one step in a chain that can inspect, transform, or short-circuit
/// an incoming request or outgoing response.
///
/// Because `Middleware` conforms to `Sendable`, implementations are safe to
/// share across concurrent request-handling tasks.
///
/// Typical uses include:
/// - Authentication and authorisation checks
/// - Request logging and metrics collection
/// - Response compression or content negotiation
/// - Rate limiting and throttling
///
/// ### Example
///
/// ```swift
/// struct AuthMiddleware: Middleware {
///     func handle(_ request: Request, next: @Sendable (Request) async throws -> Response) async throws -> Response {
///         guard let token = request.headers["Authorization"] else {
///             throw HTTPError.unauthorized
///         }
///         try await verifyToken(token)
///         return try await next(request)
///     }
/// }
/// ```
public protocol Middleware: Sendable {

    /// The request value type processed by this middleware.
    associatedtype Request: Sendable

    /// The response value type produced by this middleware.
    associatedtype Response: Sendable

    /// Intercepts a request and either forwards it or short-circuits the pipeline.
    ///
    /// - Parameters:
    ///   - request: The incoming request value.
    ///   - next: The next pipeline step to call when forwarding the request.
    /// - Returns: The response generated by this middleware or downstream handlers.
    /// - Throws: Any error raised by middleware logic or downstream handlers.
    func handle(
        _ request: Request,
        next: @Sendable (Request) async throws -> Response
    ) async throws -> Response
}
