/// A node that renders reactive text content bound to a state or computed
/// property.
///
/// `ReactiveTextNode` renders a `<span>` element whose text content is
/// kept in sync with a client-side signal. During server-side rendering,
/// it outputs the current value as static text inside the span. On the
/// client, the Score runtime emits a `Score.effect` that updates the
/// element's `textContent` whenever the bound signal changes.
///
/// You typically don't create `ReactiveTextNode` directly. Instead, use
/// the `$<name>` computed properties generated by the `@State` and
/// `@Computed` macros:
///
/// ```swift
/// struct Counter: Element {
///     @State var count = 0
///
///     var body: some Node {
///         $count  // ReactiveTextNode bound to "count"
///     }
/// }
/// ```
///
/// The rendered HTML includes a `data-bind` attribute that the runtime
/// uses to locate the element:
///
/// ```html
/// <span data-bind="count">0</span>
/// ```
public struct ReactiveTextNode: Node, Sendable {

    /// The name of the `@State` or `@Computed` property to bind.
    public let bindingName: String

    /// The server-rendered text content.
    public let text: String

    /// Creates a reactive text node.
    ///
    /// - Parameters:
    ///   - name: The name of the state or computed property.
    ///   - text: The initial text to render on the server.
    public init(name: String, text: String) {
        self.bindingName = name
        self.text = text
    }

    /// Primitive node — does not compose further.
    public var body: Never { fatalError() }
}
