/// Marks a function as a client-side action.
///
/// `@Action` is an attached peer macro that generates an
/// `ActionDescriptor` alongside the annotated function. The macro
/// automatically translates the Swift function body into equivalent
/// JavaScript signal operations.
///
/// ### Supported Patterns
///
/// - `property.toggle()` → `property.set(!property.get())`
/// - `property += value` → `property.set(property.get() + value)`
/// - `property -= value` → `property.set(property.get() - value)`
/// - `property = value` → `property.set(value)`
///
/// ### Usage
///
/// ```swift
/// struct LikeButton: Element {
///     @State var liked = false
///     @State var count = 0
///
///     @Action mutating func toggle() {
///         liked.toggle()
///         count += liked ? 1 : -1
///     }
///
///     var body: some Node {
///         Button { liked ? "Unlike" : "Like" }
///             .on(.click, action: "toggle")
///     }
/// }
/// ```
@attached(peer, names: prefixed(_action_))
public macro Action() = #externalMacro(module: "ScoreMacros", type: "ActionMacro")

/// Metadata generated by the `@Action` macro for each action function.
///
/// The ``JSEmitter`` discovers `ActionDescriptor` instances via Mirror
/// to determine which functions should be emitted as JavaScript actions.
public struct ActionDescriptor: Sendable {

    /// The name of the action function.
    public let name: String

    /// The JavaScript function body to emit on the client.
    ///
    /// Populated automatically by the macro's Swift-to-JS translator.
    /// When empty, the emitted function has no body.
    public let body: String

    /// Creates an action descriptor.
    ///
    /// - Parameters:
    ///   - name: The function name this descriptor represents.
    ///   - body: The JavaScript function body. Defaults to empty.
    public init(name: String, body: String = "") {
        self.name = name
        self.body = body
    }
}
