/// Marks a function as a client-side action.
///
/// `@Action` is an attached peer macro that generates an
/// `ActionDescriptor` alongside the annotated function. The macro
/// automatically translates the Swift function body into equivalent
/// JavaScript signal operations.
///
/// ### Supported Patterns
///
/// - `property.toggle()` → `property.set(!property.get())`
/// - `property += value` → `property.set(property.get() + value)`
/// - `property -= value` → `property.set(property.get() - value)`
/// - `property = value` → `property.set(value)`
///
/// ### Usage
///
/// ```swift
/// struct LikeButton: Element {
///     @State var liked = false
///     @State var count = 0
///
///     @Action mutating func toggle() {
///         liked.toggle()
///         count += liked ? 1 : -1
///     }
///
///     var body: some Node {
///         Button { liked ? "Unlike" : "Like" }
///             .on(.click, action: $toggle)
///     }
/// }
/// ```
@attached(peer, names: arbitrary)
public macro Action() = #externalMacro(module: "ScoreMacros", type: "ActionMacro")

/// Metadata generated by the `@Action` macro for each action function.
///
/// The ``JSEmitter`` discovers `ActionDescriptor` instances via Mirror
/// to determine which functions should be emitted as JavaScript actions.
public struct ActionDescriptor: Sendable {

    /// The name of the action function.
    public let name: String

    /// The JavaScript function body to emit on the client.
    ///
    /// Populated automatically by the macro's Swift-to-JS translator.
    /// When empty, the emitted function has no body.
    public let body: String

    /// The parameter names of the action function.
    ///
    /// When non-empty, the emitted JavaScript function accepts these named
    /// parameters. Event bindings with `args:` pass values positionally.
    public let parameters: [String]

    /// Creates an action descriptor.
    ///
    /// - Parameters:
    ///   - name: The function name this descriptor represents.
    ///   - body: The JavaScript function body. Defaults to empty.
    ///   - parameters: The function parameter names. Defaults to empty.
    public init(name: String, body: String = "", parameters: [String] = []) {
        self.name = name
        self.body = body
        self.parameters = parameters
    }
}

/// A type-safe reference to an `@Action`-annotated function.
///
/// The `@Action` macro generates a static `$<name>` property of this type
/// for each action, enabling type-safe event bindings:
///
/// ```swift
/// @Action mutating func toggle() { liked.toggle() }
///
/// // Generated by the macro:
/// // static let $toggle = ActionRef("toggle")
///
/// // Type-safe usage:
/// Button { "Toggle" }
///     .on(.click, action: $toggle)
/// ```
///
/// This eliminates the risk of typos in string-based action names while
/// remaining backward-compatible with the existing string API.
public struct ActionRef: Sendable {

    /// The name of the action function.
    public let name: String

    /// Creates an action reference.
    ///
    /// - Parameter name: The function name this reference points to.
    public init(_ name: String) {
        self.name = name
    }
}
