/// Marks a function as a client-side action.
///
/// `@Action` is an attached peer macro that generates an
/// `ActionDescriptor` alongside the annotated function. The
/// ``JSEmitter`` discovers these descriptors via Mirror reflection
/// to emit corresponding JavaScript action functions on the client.
///
/// ### Usage
///
/// ```swift
/// struct LikeButton: Element {
///     @State var liked = false
///     @State var count = 0
///
///     @Action func toggle() {
///         liked.toggle()
///         count += liked ? 1 : -1
///     }
///
///     var body: some Node {
///         Button { liked ? "Unlike" : "Like" }
///             .on(.click, action: "toggle")
///     }
/// }
/// ```
@attached(peer, names: prefixed(_action_))
public macro Action() = #externalMacro(module: "ScoreMacros", type: "ActionMacro")

/// Metadata generated by the `@Action` macro for each action function.
///
/// The ``JSEmitter`` discovers `ActionDescriptor` instances via Mirror
/// to determine which functions should be emitted as JavaScript actions.
public struct ActionDescriptor: Sendable {

    /// The name of the action function.
    public let name: String

    /// Creates an action descriptor.
    ///
    /// - Parameter name: The function name this descriptor represents.
    public init(name: String) {
        self.name = name
    }
}
