/// Marks a computed property for client-side reactive derivation.
///
/// `@Computed` is an attached peer macro that generates a
/// `ComputedDescriptor` alongside the annotated computed property.
/// The macro automatically translates the Swift getter body into
/// equivalent JavaScript signal operations.
///
/// During server-side rendering, the property evaluates normally as a
/// Swift computed property. On the client, the Score runtime emits a
/// `Signal.Computed` that automatically re-evaluates when any upstream
/// `State` signals it depends on change.
///
/// ### Supported Patterns
///
/// - Identifier references → `name.get()`
/// - Ternary expressions → `cond ? then : else`
/// - Binary operators → `+`, `-`, `*`, `/`, `%`, `==`, `!=`, `<`, `>`, etc.
/// - Boolean, integer, float, and string literals
///
/// ### Usage
///
/// ```swift
/// struct Counter: Element {
///     @State var count = 0
///
///     @Computed var label: String { count > 0 ? "Active" : "Idle" }
///
///     var body: some Node {
///         $label
///     }
/// }
/// ```
@attached(peer, names: arbitrary)
public macro Computed() = #externalMacro(module: "ScoreMacros", type: "ComputedMacro")

/// Variant of `@Computed` that provides a manual JavaScript override.
///
/// Use this for computed properties whose getter the auto-translator
/// cannot handle, such as string interpolation or complex expressions.
///
/// - Parameter js: The JavaScript expression to emit on the client.
@attached(peer, names: arbitrary)
public macro Computed(js: String) = #externalMacro(module: "ScoreMacros", type: "ComputedMacro")

/// Metadata generated by the `@Computed` macro for each computed property.
///
/// The ``JSEmitter`` discovers `ComputedDescriptor` instances via Mirror
/// to determine which properties should be emitted as JavaScript computeds.
public struct ComputedDescriptor: Sendable {

    /// The name of the computed property.
    public let name: String

    /// The JavaScript expression to emit as the computed body.
    ///
    /// Populated automatically by the macro's Swift-to-JS translator.
    /// When empty, the computed is emitted with a self-referencing
    /// placeholder.
    public let body: String

    /// Creates a computed descriptor.
    ///
    /// - Parameters:
    ///   - name: The property name this descriptor represents.
    ///   - body: The JavaScript expression body. Defaults to empty.
    public init(name: String, body: String = "") {
        self.name = name
        self.body = body
    }
}
