/// A protocol for structs used as grouped `@State` that support
/// per-field reactive signals and `.reset()` functionality.
///
/// Conform your form/edit structs to `Resettable` to enable:
/// - Per-field reactive signals (e.g., `input_title`, `input_description`)
/// - A reset function that restores all fields to initial values
/// - Sub-property binding via `$input.title` syntax
///
/// ### Example
///
/// ```swift
/// struct ItemForm: Resettable {
///     var title: String = ""
///     var description: String = ""
/// }
///
/// // In a page or component:
/// @State var input = ItemForm()
///
/// @Action func addItem() {
///     items.create(["title": input.title, "description": input.description])
///     input.reset()
/// }
///
/// Input(type: .text, value: $input.title)
/// ```
public protocol Resettable: Sendable {

    /// Creates a default instance for field inspection.
    init()

    /// The fields of this struct and their JavaScript initial values.
    ///
    /// The default implementation uses `Mirror` to inspect a default instance
    /// and converts each field's value to a JavaScript literal. Override only
    /// if auto-detection doesn't produce the correct output.
    static var jsFields: [(name: String, initialValue: String)] { get }
}

extension Resettable {

    /// Auto-derives field names and JavaScript initial values from a default instance.
    public static var jsFields: [(name: String, initialValue: String)] {
        let instance = Self()
        let mirror = Mirror(reflecting: instance)
        return mirror.children.compactMap { child in
            guard let name = child.label else { return nil }
            // Skip private/underscore fields generated by macros
            guard !name.hasPrefix("_") else { return nil }
            let jsValue = jsLiteral(for: child.value)
            return (name, jsValue)
        }
    }

    /// Swift-side stub for `.reset()` — the actual implementation runs as
    /// JavaScript (`base_reset()`) which restores all fields to their
    /// initial values. This method exists solely to satisfy the Swift
    /// type checker inside `@Action` bodies.
    public mutating func reset() {}

    /// Converts a Swift value to a JavaScript literal string.
    private static func jsLiteral(for value: Any) -> String {
        switch value {
        case let s as String: return "\"\(s)\""
        case let i as Int: return "\(i)"
        case let d as Double: return "\(d)"
        case let b as Bool: return b ? "true" : "false"
        default: return "\"\""
        }
    }
}

/// Metadata generated by the `@State` macro for grouped state properties.
///
/// When `@State` is applied to a property whose type conforms to
/// ``Resettable``, a `GroupedStateDescriptor` is generated instead of a
/// plain `StateDescriptor`. The ``JSEmitter`` discovers these via Mirror
/// and emits per-field signals plus a reset function.
public struct GroupedStateDescriptor: Sendable {

    /// The base name of the grouped state property.
    public let name: String

    /// The fields and their JavaScript initial values.
    public let fields: [(name: String, initialValue: String)]

    /// Creates a grouped state descriptor.
    public init(name: String, fields: [(name: String, initialValue: String)]) {
        self.name = name
        self.fields = fields
    }
}

/// A projection of a grouped `@State` property providing per-field
/// reactive bindings.
///
/// Access via the `$` prefix on a grouped state property:
///
/// ```swift
/// @State var input = ItemForm()
/// Input(type: .text, value: $input.title)
/// ```
@dynamicMemberLookup
public struct GroupedStateProjection: Sendable {

    /// The base name of the grouped state property.
    public let name: String

    /// Creates a grouped state projection.
    public init(name: String) {
        self.name = name
    }

    /// Returns a reactive text node for the named field.
    ///
    /// The binding name follows the pattern `baseName_fieldName`.
    public subscript(dynamicMember field: String) -> ReactiveTextNode {
        ReactiveTextNode(name: "\(name)_\(field)", text: "")
    }
}
