/// Marks a stored property as reactive client-side state.
///
/// `@State` is an attached macro that transforms a stored property into
/// a reactive signal. During server-side rendering, the property behaves
/// as a normal stored value. On the client, the Score runtime emits a
/// `Signal.State` that tracks reads and writes, allowing the reactive
/// engine to update only the DOM nodes that depend on the value.
///
/// The macro generates:
/// - A backing stored property for the value
/// - A `StateDescriptor` peer discovered by the ``JSEmitter`` via Mirror
/// - A `$<name>` computed property returning a ``ReactiveTextNode``
///   for use in node builder bodies
///
/// ### Usage
///
/// ```swift
/// struct Counter: Element {
///     @State var count = 0
///
///     @Action mutating func increment() {
///         count += 1
///     }
///
///     var body: some Node {
///         Stack {
///             $count
///             Button { "+" }
///                 .on(.click, action: "increment")
///         }
///     }
/// }
/// ```
///
/// The `$count` property renders the current value of `count` inside
/// a `<span>` element that the runtime keeps in sync with the signal.
@attached(accessor)
@attached(peer, names: arbitrary)
public macro State() = #externalMacro(module: "ScoreMacros", type: "StateMacro")

/// Variant of `@State` that persists its value to `localStorage`.
///
/// On page load, the state is initialized from the stored value if one
/// exists. Whenever the state changes, the new value is automatically
/// written back to `localStorage` under the given key.
///
/// Use ``StorageKey/theme`` for theme persistence, which adds automatic
/// `prefers-color-scheme` fallback and `data-theme` attribute management:
///
/// ```swift
/// @State(persisted: .theme) var isDark = false
/// ```
///
/// Use a custom string key for general-purpose persistence:
///
/// ```swift
/// @State(persisted: "my-setting") var volume = 50
/// ```
///
/// - Parameter persisted: The storage key used for persistence.
@attached(accessor)
@attached(peer, names: arbitrary)
public macro State(persisted: StorageKey) = #externalMacro(module: "ScoreMacros", type: "StateMacro")

/// Identifies a `localStorage` key for ``State`` persistence.
///
/// Use the ``theme`` constant for automatic dark-mode handling, or
/// initialize with a string literal for custom persistence keys:
///
/// ```swift
/// @State(persisted: .theme) var isDark = false
/// @State(persisted: "volume") var volume = 50
/// ```
public struct StorageKey: Sendable, ExpressibleByStringLiteral {

    /// The `localStorage` key string.
    public let rawValue: String

    /// Whether this key represents the built-in theme toggle.
    ///
    /// When `true`, the emitter adds `prefers-color-scheme` fallback
    /// initialization and automatic `data-theme` attribute management.
    public let isTheme: Bool

    /// The reserved theme persistence key.
    ///
    /// Using this key enables automatic `prefers-color-scheme` detection
    /// and `data-theme` attribute updates on the document element.
    public static let theme = StorageKey(rawValue: "as-theme", isTheme: true)

    /// Creates a storage key from a string literal.
    ///
    /// - Parameter value: The `localStorage` key string.
    public init(stringLiteral value: String) {
        self.rawValue = value
        self.isTheme = false
    }

    /// Creates a storage key with explicit theme flag.
    ///
    /// - Parameters:
    ///   - rawValue: The `localStorage` key string.
    ///   - isTheme: Whether this key represents the theme toggle.
    public init(rawValue: String, isTheme: Bool = false) {
        self.rawValue = rawValue
        self.isTheme = isTheme
    }
}

/// Metadata generated by the `@State` macro for each state property.
///
/// The ``JSEmitter`` discovers `StateDescriptor` instances via Mirror
/// reflection to determine which properties should be emitted as
/// JavaScript signals on the client.
public struct StateDescriptor: Sendable {

    /// The name of the state property.
    public let name: String

    /// The initial value formatted as a JavaScript literal.
    ///
    /// For example, `0` becomes `"0"`, `"hello"` becomes `"\"hello\""`,
    /// and `true` becomes `"true"`.
    public let jsInitialValue: String

    /// The `localStorage` key for persistence.
    ///
    /// When non-empty, the emitter initializes the state from
    /// `localStorage` and auto-saves changes back.
    public let storageKey: String

    /// Whether this state uses the built-in theme persistence behavior.
    ///
    /// When `true`, the emitter adds `prefers-color-scheme` fallback
    /// and `data-theme` attribute management to the generated JavaScript.
    public let isTheme: Bool

    /// Creates a state descriptor.
    ///
    /// - Parameters:
    ///   - name: The property name this descriptor represents.
    ///   - jsInitialValue: The initial value as a JavaScript literal.
    ///   - storageKey: A `localStorage` key for persistence. Defaults to empty.
    ///   - isTheme: Whether this state uses theme persistence. Defaults to `false`.
    public init(name: String, jsInitialValue: String, storageKey: String = "", isTheme: Bool = false) {
        self.name = name
        self.jsInitialValue = jsInitialValue
        self.storageKey = storageKey
        self.isTheme = isTheme
    }
}
