/// Marks a stored property as reactive client-side state.
///
/// `@State` is an attached macro that transforms a stored property into
/// a reactive signal. During server-side rendering, the property behaves
/// as a normal stored value. On the client, the Score runtime emits a
/// `Signal.State` that tracks reads and writes, allowing the reactive
/// engine to update only the DOM nodes that depend on the value.
///
/// The macro generates:
/// - A backing stored property for the value
/// - A `StateDescriptor` peer discovered by the ``JSEmitter`` via Mirror
/// - A `$<name>` computed property returning a ``ReactiveTextNode``
///   for use in node builder bodies
///
/// ### Usage
///
/// ```swift
/// struct Counter: Element {
///     @State var count = 0
///
///     @Action mutating func increment() {
///         count += 1
///     }
///
///     var body: some Node {
///         Stack {
///             $count
///             Button { "+" }
///                 .on(.click, action: "increment")
///         }
///     }
/// }
/// ```
///
/// The `$count` property renders the current value of `count` inside
/// a `<span>` element that the runtime keeps in sync with the signal.
@attached(accessor)
@attached(peer, names: arbitrary)
public macro State() = #externalMacro(module: "ScoreMacros", type: "StateMacro")

/// Variant of `@State` that persists its value to `localStorage`.
///
/// On page load, the state is initialized from the stored value if one
/// exists. Whenever the state changes, the new value is automatically
/// written back to `localStorage` under the given key.
///
/// - Parameter persisted: The `localStorage` key used for persistence.
@attached(accessor)
@attached(peer, names: arbitrary)
public macro State(persisted: String) = #externalMacro(module: "ScoreMacros", type: "StateMacro")

/// Metadata generated by the `@State` macro for each state property.
///
/// The ``JSEmitter`` discovers `StateDescriptor` instances via Mirror
/// reflection to determine which properties should be emitted as
/// JavaScript signals on the client.
public struct StateDescriptor: Sendable {

    /// The name of the state property.
    public let name: String

    /// The initial value formatted as a JavaScript literal.
    ///
    /// For example, `0` becomes `"0"`, `"hello"` becomes `"\"hello\""`,
    /// and `true` becomes `"true"`.
    public let jsInitialValue: String

    /// The `localStorage` key for persistence.
    ///
    /// When non-empty, the emitter initializes the state from
    /// `localStorage` and auto-saves changes back.
    public let storageKey: String

    /// Creates a state descriptor.
    ///
    /// - Parameters:
    ///   - name: The property name this descriptor represents.
    ///   - jsInitialValue: The initial value as a JavaScript literal.
    ///   - storageKey: A `localStorage` key for persistence. Defaults to empty.
    public init(name: String, jsInitialValue: String, storageKey: String = "") {
        self.name = name
        self.jsInitialValue = jsInitialValue
        self.storageKey = storageKey
    }
}
